# Latte - light theme for Foot
# Include in foot.ini: include=/path/to/latte.ini

initial-color-theme=light

[colors-light]
foreground=1F1C16
background=F5F4F0
regular0=1F1C16
regular1=9E3E3E
regular2=387050
regular3=7D6820
regular4=3468A8
regular5=6438A0
regular6=287070
regular7=746C62
bright0=6E6459
bright1=B85555
bright2=509058
bright3=968232
bright4=4C80BE
bright5=7E52BA
bright6=388888
bright7=FEFCFA