# Latte - light theme for Kitty

background #F5F4F0
foreground #1F1C16
selection_background #D5D2CB
selection_foreground #1F1C16

cursor #1F1C16
cursor_text_color #F5F4F0

url_color #746C62

active_border_color #91887D
inactive_border_color #E8E7E3

tab_bar_background #F5F4F0
active_tab_background #D5D2CB
active_tab_foreground #1F1C16
inactive_tab_background #E8E7E3
inactive_tab_foreground #6E6459

color0 #1F1C16
color1 #9E3E3E
color2 #387050
color3 #7D6820
color4 #3468A8
color5 #6438A0
color6 #287070
color7 #746C62

color8 #6E6459
color9 #B85555
color10 #509058
color11 #968232
color12 #4C80BE
color13 #7E52BA
color14 #388888
color15 #FEFCFA

color16 #8F5D22
color17 #943A68